FROM node:latest
WORKDIR /usr/src
ADD ./package*.json /usr/src
RUN npm install
RUN npm run build

FROM nginx:latest
WORKDIR /usr/src
RUN mv /usr/src/build /usr/share/nginx/html
COPY nginx_deployed.conf /etc/nginx/conf.d/default.conf
